<a href="https://colab.research.google.com/github/shambhavishanbhag1910/Agent-Observability-Evaluations/blob/main/LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def add_vectors(vectora, vectorb):
    return np.add(vectora, vectorb)

def subtract_vectors(vectora, vectorb):
    return np.subtract(vectora, vectorb)

def multiply_vectors(vectora, vectorb):
    return np.multiply(vectora, vectorb)

# Example
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

print("Vector_a=",vector_a)
print("Vector_b=",vector_b)
result_addition = add_vectors(vector_a, vector_b)
result_subtraction = subtract_vectors(vector_a, vector_b)
result_multiplication = multiply_vectors(vector_a, vector_b)

print("Vector Addition:", result_addition)
print("Vector Subtraction:", result_subtraction)
print("Vector Multiplication:", result_multiplication)

Vector_a= [1 2 3]
Vector_b= [4 5 6]
Vector Addition: [5 7 9]
Vector Subtraction: [-3 -3 -3]
Vector Multiplication: [ 4 10 18]


In [ ]:
import numpy as np
# take a 3x2 matrix
A = [[12, 7],
	[4, 5],
	[7, 8]]

# take a 2x1 matrix
B = [[5],
	[6]]

# result will be 3x4

result= [[0,0,0,0],
		[0,0,0,0],
		[0,0,0,0]]

result = np.dot(A,B)

for r in result:
	print(r)


[102]
[50]
[83]


In [ ]:
import tensorflow as tf

A1 =tf.constant([1,2,3,4])
B1 =tf.constant([3,4,5,6])
C1 =tf.multiply(A1,B1)

C1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  8, 15, 24], dtype=int32)>

In [ ]:
import tensorflow as tf
A1 = tf.constant([[2,24],[2,24],[2,57]])
B1= tf.constant([[1000],[150]])
C1= tf.matmul(A1,B1)
C1

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 5600],
       [ 5600],
       [10550]], dtype=int32)>

In [ ]:
wv=[1,2,3,4,5,6,7,8,9]
vx=[1,9,8,4,5,6,7,3,2]
xv=np.random.rand(10)

In [ ]:
def v_v(wv, xv):
  total=0
  for w, x in zip(wv,vx):
    total += w*x
    return total

In [ ]:
w=xv
x=xv
z=v_v(w,x)
print(np.sum(z))

0.28543612671621044
